.\" groink man page
.\"
.TH "GROINK" "8" "" "GroinK 0.1BETA1" ""

.SH NAME
GroinK \- advanced sniffer

.SH SYNOPSIS
.B groink [OPTIONS] [SCRIPT_NAME [ARG1[=VAL1] [ARG2[=VAL2] ...]]]

.SH DESCRIPTION
.TP
asd

.SH OPTIONS
.TP
asd

.SH EXAMPLES
.TP
asd

.SH BUGS
.PP
Please send bug-report, patches or suggestions to <decrew@indivia.net>

.SH AUTHOR
Rocco 'LordZen' Folino <lordzen@autistici.org>

.SH WEBSITE
http://decrew.indivia.net/groink
